### PR TITLE
Encourage the user to enter a short crash description

### LINKED ISSUE #26: Encourage the user to enter a short description of what they were doing when they crashed
While a user can technically do so at current by editing it into one of the log tabs we should encourage it with a separate field. Depending on the upload service it could go in its own section (Gist) or just get be pasted at the top of a multi-item pastebin entry.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29325194-encourage-the-user-to-enter-a-short-description-of-what-they-were-doing-when-they-crashed?utm_campaign=plugin&utm_content=tracker%2F1626462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1626462&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by rzats**
Fixes #26 

Adds an additional panel just after the user finishes editing the log file, prompting (and forcing) them to input some additional info about the issue. Said info is then appended to the beginning of the log.

UI screenshot for reference:

UI screenshot

### CODE REVIEW

**Comment by msteiger** [comment]
Thanks - will have a look asap!

File: src/main/java/org/terasology/crashreporter/RootPanel.java [hunk 1]
```diff
@@ -16,35 +16,26 @@
...
-import java.awt.GridLayout;
-import java.awt.Window;
+import org.terasology.crashreporter.pages.ErrorMessagePanel;
+import org.terasology.crashreporter.pages.FinalActionsPanel;
+import org.terasology.crashreporter.pages.UploadPanel;
+import org.terasology.crashreporter.pages.UserInfoPanel;
+import org.terasology.gui.JImage;
+import org.terasology.gui.RXCardLayout;
+
+import javax.swing.*;
```
Comment (msteiger) [inline src/main/java/org/terasology/crashreporter/RootPanel.java]: No wildcard imports, please.

File: src/main/java/org/terasology/crashreporter/pages/UserInfoPanel.java [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+
+        userMessageArea = new JTextArea();
+        userMessageArea.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
+        userMessageArea.setFont(getFont().deriveFont(Font.PLAIN).deriveFont(12f));
+
+        userMessageArea.getDocument().addDocumentListener(new DocumentListener() {
+            @Override
+            public void insertUpdate(DocumentEvent e) {
+                additionalInfoPresent = true;
+                changeStatus();
```
Comment (msteiger) [inline src/main/java/org/terasology/crashreporter/pages/UserInfoPanel.java]: I'd rather rename it to `refreshStatus` and check whether the document is empty or not in that method. The `additionalInfoPresent` flag is obsolete then.

**Comment by msteiger** [comment]
Do you remember where the new icon image is from? You might want to add licence info, etc. to the [attribution.txt](https://github.com/MovingBlocks/CrashReporter/blob/develop/src/main/resources/icons/attribution.txt) file.

Looks good to me in general. Just a few minor issues.

**Comment by msteiger** [comment]
Thanks, @rzats - I tweaked a few things so it would look consistent with the error log panel.
